/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.10).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.lazybot.microservices.map.api.api;

import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2020-02-10T10:49:33.117Z")

@Api(value = "position", description = "the position API")
public interface PositionApi {

    @ApiOperation(value = "Get position of bots", nickname = "getPositions", notes = "", response = String.class, responseContainer = "List", tags={ "position", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful operation", response = String.class, responseContainer = "List") })
    @RequestMapping(value = "/position",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.GET)
    ResponseEntity<List<String>> getPositions(@NotNull @ApiParam(value = "Precise the quantity of bots you want. If it's many you'll have to give a list of the id of the bots that you want, if it's all all the bots will be returned", required = true, allowableValues = "many, all") @Valid @RequestParam(value = "quantity", required = true) List<String> quantity,@ApiParam(value = "Status values that need to be considered for filter") @Valid @RequestParam(value = "botsId", required = false) List<Integer> botsId);


    @ApiOperation(value = "Give a position where the bots will have to go", nickname = "goToPosition", notes = "", response = String.class, responseContainer = "List", tags={ "position", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful operation", response = String.class, responseContainer = "List") })
    @RequestMapping(value = "/position",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<List<String>> goToPosition(@NotNull @ApiParam(value = "Give the list of id of bots that will have to go to the position", required = true) @Valid @RequestParam(value = "bots", required = true) List<Integer> bots,@ApiParam(value = "Status values that need to be considered for filter") @Valid @RequestParam(value = "position", required = false) List<Integer> position);

}
